version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=tests
    ports:
      - "3307:3306"
    networks:
      - backend

  event-service:
    container_name: event-service
    depends_on:
      - mysqldb
    image: denpool/event-service:0.0.1
    ports:
      - "9000:9000"
    networks:
      - backend
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?serverTimezone=UTC",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "12345",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect"
      }'

  storage-service:
    container_name: storage-service
    image: denpool/storage-service:0.0.1
    restart: always
    ports:
      - "6500:6500"
    networks:
      - backend

networks:
  backend:
volumes:
  db-data: