spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/event_service?serverTimezone=UTC
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: event-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 6MB
  cloud:
    openfeign:
      client:
        config:
          storage-service:
            url: http://localhost:6500
server:
  port: 9000
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
